let productsJson = [
    {id:1, name:'Ração para Gatos Adultos Castrados Sabor Frango', brand: 'Golden', img:'assets/images/ProductsJson/1.png', price:30.95, sizes:['1g', '2kg', '10kg'], description:'- Indicada para gatos; - Contém fórmula específica para felinos castrados; - Auxilia no controle de peso; - Proporciona saúde ao trato urinário, - Livre de corantes e aromatizantes artificiais'},
    {id:2, name:'Antipulgas e Carrapatos Bravecto MSD para Cães', brand: 'Bravecto', img:'assets/images/ProductsJson/2.png', price:214.99, sizes:['1g', '2kg', '10kg'], description:'- Indicado para cães; - Acaba com a infestação de carrapatos e pulgas; - Rápida ação;  - Efeito prolongado por 12 semanas;'},
    {id:3, name:'Ração Mix de Carnes para Gatos Adultos', brand: 'Whiskas', img:'assets/images/ProductsJson/3.png', price:56.99, sizes:['1g', '2kg', '10kg'], description:'- Indicada para gatos adultos; - 100% completa e balanceada; - Fórmula livre de corantes artificiais; - Minerais controlados para ajudar a manter o trato urinário saudável;'},
    {id:4, name:'Ração Golden Special Sabor Frango e Carne para Cães Adultos', brand: 'Golden', img:'assets/images/ProductsJson/4.png', price:142.99, sizes:['1g', '2kg', '10kg'], description:'- Músculos fortes; - Fórmula rica em nutrientes e minerais; - Promove maior equilíbrio intestinal; - Reduz o volume e odor das fezes;'},
    {id:5, name:'Ração Royal Canin Boxer Puppy', brand: 'Royal Canin', img:'assets/images/ProductsJson/5.png', price:242.99, sizes:['1g', '2kg', '10kg'], description:'- Músculos fortes; - Fórmula rica em nutrientes e minerais; - Promove maior equilíbrio intestinal; - Reduz o volume e odor das fezes;'},
    {id:6, name:'Ração para Cães Filhotes Sabor Frango', brand: 'Premiere', img:'assets/images/ProductsJson/6.png', price:212.99, sizes:['1g', '2kg', '10kg'], description:'- Indicada para cães filhotes; - Ideal para os pets de graças grandes; - Oferece suporte aos ossos e articulações; - Mantém a saúde do trato intestinal;'},
    {id:7, name:'Ração Nutrópica Natural para Hamster', brand: 'Nutrópica', img:'assets/images/ProductsJson/7.png', price:24.99, sizes:['300g', '900g'], description:'- Indicada para hamster; - Não contem transgênicos; - Adaptado para dietas ricas em fibras; - Sabor inigualável; '},
    {id:8, name:'Aditivo Kets Antiodor para Gatos', brand: 'AlfaPet', img:'assets/images/ProductsJson/8.png', price:24.99, sizes:['300g', '900g'], description:'- Indicada para hamster; - Não contem transgênicos; - Adaptado para dietas ricas em fibras; - Sabor inigualável; '},
    {id:9, name:'Ração para Cães Adultos de Médio e Grande Porte Sabor Ovelha e Arroz', brand: 'GranPlus', img:'assets/images/ProductsJson/9.png', price:57.99, sizes:['1g', '2kg', '10kg'], description:'- Indicado para gatos; - Ajuda a eliminar as bactérias que causam mau cheiro; - Auxilia a manter a areia seca; '},
    {id:10, name:'Ração Golden para Cães Adultos Seleção Natural Abóbora', brand: 'Golden', img:'assets/images/ProductsJson/10.png', price:65.99, sizes:['1g', '2kg', '10kg'], description:'- Indicada para cães adultos; - Feita com ingredientes ricos em fibras e minerais; - Contem ômegas que proporcionam mais saúde para pele e pelagem; - Auxilia na redução do odor das fezes,'},
    {id:11, name:'Ração Farinhada com Mel e Ovos para Calopsita', brand: 'Nutrópica', img:'assets/images/ProductsJson/11.png', price:32.99, sizes:['300g', '900kg', '1kg'], description:'- Indicada para Calopsitas; - À base de mel, ovos e grãos integrais (aveia, trigo, trigo sarraceno); - Proporciona aos pets nutrientes necessários para sua dieta;'},
    {id:12, name:'Ração Úmida Lata para Gatos Adultos Sabor Atum ao Molho', brand: 'Whiskas', img:'assets/images/ProductsJson/12.png', price:9.69, sizes:['1290g'], description:'- Indicada para Calopsitas; - À base de mel, ovos e grãos integrais (aveia, trigo, trigo sarraceno); - Proporciona aos pets nutrientes necessários para sua dieta;'},
];